[Personal]
source        = imaps://niceniceytube%40gmail.com@imap.gmail.com:993
outgoing      = smtp://niceniceytube%40gmail.com@smtp.gmail.com:587
default       = INBOX
from          = walid <niceniceytube@gmail.com>
cache-headers = true

source-cred-cmd = pass ggl_app_pass
outgoing-cred-cmd = pass ggl_app_pass

