# Generated by Powerlevel10k configuration wizard on 2026-01-09 at 22:39 CET.
# Customized with Nord theme and fancy styling

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Nord Color Palette
  local nord0='#2E3440'   # Polar Night - darkest
  local nord1='#3B4252'   # Polar Night
  local nord2='#434C5E'   # Polar Night
  local nord3='#4C566A'   # Polar Night - lightest
  local nord4='#D8DEE9'   # Snow Storm
  local nord5='#E5E9F0'   # Snow Storm
  local nord6='#ECEFF4'   # Snow Storm - lightest
  local nord7='#8FBCBB'   # Frost - teal
  local nord8='#88C0D0'   # Frost - cyan
  local nord9='#81A1C1'   # Frost - blue
  local nord10='#5E81AC'  # Frost - dark blue
  local nord11='#BF616A'  # Aurora - red
  local nord12='#D08770'  # Aurora - orange
  local nord13='#EBCB8B'  # Aurora - yellow
  local nord14='#A3BE8C'  # Aurora - green
  local nord15='#B48EAD'  # Aurora - purple

  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                       # current directory
    vcs                       # git status
    newline                   # \n
    prompt_char               # λ symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                    # exit code of last command
    command_execution_time    # previous command duration
    background_jobs           # background jobs indicator
    virtualenv                # python virtual environment
    time                      # current time
    newline                   # \n
  )

  # Basic style options
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # Add spacing between prompts
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Lambda prompt symbol - BOLD, Nord cyan when ok, red when error
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$nord8
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$nord11
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='%Bλ%b'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='%B❮%b'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='%B❮%b'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

  # Status - show error codes
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$nord14
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$nord11
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=$nord12
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=$nord11

  # Directory - Nord blue, show FULL path (no shortening except ~)
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$nord9
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$nord10
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$nord8
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  # Show full path
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
  # Icons for special directories (removed emojis)
  typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '~/nixos-dotfiles(/*)#'  DOTFILES  ''
    '~/*'                    HOME      ''
  )
  typeset -g POWERLEVEL9K_DIR_DOTFILES_FOREGROUND=$nord15
  typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=$nord9

  # Git status - colorful indicators
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$nord14
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$nord7
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$nord13
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$nord3
  
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
  typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=5
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.05

  # Python virtualenv - Nord green (no emoji)
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$nord14
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  # Command execution time - Nord yellow (no emoji)
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$nord13

  # Background jobs - Nord orange (no emoji)
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$nord12

  # Context - Always show user@host, Nord purple when root, cyan when user
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$nord11
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$nord8
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%n@%m%b'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true

  # Time - Nord frost (no emoji)
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$nord7
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Transient prompt - clean previous prompts
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
bindkey '^ ' autosuggest-accept
bindkey '^E' autosuggest-accept
bindkey '^L' autosuggest-accept
bindkey '^N' menu-complete            
bindkey '^P' reverse-menu-complete    
bindkey '^[[Z' reverse-menu-complete  




(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
