# --- Main Colors ---
background            #191114
foreground            #efdfe2
cursor                #efdfe2
cursor_text_color     #191114

selection_background  #5a3f48
selection_foreground  #ffd9e3

url_color             #f0bc95

# --- ANSI Colors ---
color0                #191114
color1                #ffb4ab
color2                #f0bc95
color3                #e2bdc7
color4                #ffb0cb
color5                #f0bc95
color6                #e2bdc7
color7                #efdfe2

color8                #514347
color9                #93000a
color10               #623f21
color11               #5a3f48
color12               #6f334b
color13               #5a3f48
color14               #623f21
color15               #d5c2c6

# --- Starship Prompt Bubbles ---
color255              #6f334b
color254              #ffb0cb
color253              #5a3f48
color252              #e2bdc7
color251              #623f21
color250              #f0bc95
color249              #93000a
color248              #ffb4ab

color232              #ffd9e3
color233              #541d34
color234              #ffd9e3
color235              #422932
color236              #ffdcc3
color237              #48290d
color238              #ffdad6
color239              #690005
color240              #ffd9e3

# Matched with unthemed light/dark
color243              #ffb0cb
color244              #ffb4ab
color245              #514347

# --- UI Elements ---
active_tab_foreground   #541d34
active_tab_background   #ffb0cb
inactive_tab_foreground #ffd9e3
inactive_tab_background #6f334b

active_border_color     #ffb0cb
inactive_border_color   #9e8c91

# --- Marks ---
mark1_foreground        #39071f
mark1_background        #ffd9e3
mark2_foreground        #2a151d
mark2_background        #ffd9e3
mark3_foreground        #2f1500
mark3_background        #ffdcc3
