rootcolor=191114ff

bordercolor=514347ff

focuscolor=6f334bff

maximizescreencolor=e2bdc7ff

urgentcolor=ffb4abff

scratchpadcolor=f0bc95ff

globalcolor=5a3f48ff

overlaycolor=623f21ff

jump_hit_fg_color=ffd9e3ff

jump_hit_bg_color=efdfe2ff

jump_hit_border_color=ffb0cbff
