# -*- conf -*-
shell="/usr/bin/bash"
font=Envy Code R:size=11

[desktop-notifications]
command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}
[scrollback]
lines=100000
[colors-dark]
background= 111318
foreground= cdd6f4
# Regular colors
regular0= 1e1e2e
regular1= f38ba8
regular2= a6e3a1
regular3= f9e2af
regular4= 89b4fa
regular5= cba6f7
regular6= 94e2d5
regular7= bac2de

# Bright colors
bright0= 313244
bright1= f38ba8
bright2= a6e3a1
bright3= f9e2af
bright4= 89b4fa
bright5= cba6f7
bright6= 94e2d5
bright7= a6adc8
