general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
opacity = 0.8
[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 20
y = 20
