################################################
# Matugen -> ~/.config/MangoHud/MangoHud.conf
################################################

##############################
# Layout & Theme
##############################
position=top-left
table_columns=2

background_alpha=0.45
background_color={{colors.background.dark.hex_stripped}}
text_color={{colors.on_background.dark.hex_stripped}}

round_corners=10
hud_no_margin
legacy_layout=false
no_display=0

font_size=20
font_size_text=18

##############################
# FPS
##############################
fps
fps_color_change
fps_value=30,60
fps_color={{colors.error.dark.hex_stripped}},{{colors.tertiary.dark.hex_stripped}},{{colors.primary.dark.hex_stripped}}
show_fps_limit

##############################
# GPU
##############################
gpu_text=GPU
gpu_name

gpu_stats
gpu_load_change
gpu_load_value=50,90
gpu_load_color={{colors.secondary.dark.hex_stripped}},{{colors.tertiary.dark.hex_stripped}},{{colors.error.dark.hex_stripped}}

gpu_temp
gpu_power

gpu_color={{colors.secondary.dark.hex_stripped}}

##############################
# CPU
##############################
cpu_text=CPU

cpu_stats
cpu_load_change
cpu_load_value=50,90
cpu_load_color={{colors.primary.dark.hex_stripped}},{{colors.tertiary.dark.hex_stripped}},{{colors.error.dark.hex_stripped}}

cpu_temp
cpu_power

cpu_color={{colors.primary.dark.hex_stripped}}

##############################
# Memory
##############################
ram
ram_color={{colors.secondary_container.dark.hex_stripped}}

vram
vram_color={{colors.tertiary_container.dark.hex_stripped}}

##############################
# Disk I/O
##############################
io_read
io_write

##############################
# Game / System
##############################
resolution

wine
wine_color={{colors.error.dark.hex_stripped}}

media_player
media_player_color={{colors.on_secondary_container.dark.hex_stripped}}

##############################
# Bottom Graph
##############################
frame_timing=1
frametime
frametime_color={{colors.primary.dark.hex_stripped}}
